language: java

script: travis_wait 120 ./.travis-build.sh

sudo: false
## Reinstate when the build can use a standard jtreg install
# addons:
#   apt:
#     packages:
#       - jtreg

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

notifications:
  email:
    - checker-framework-dev@googlegroups.com 

git:
  depth: 3
