language: java

script: travis_wait 120 ./.travis-build.sh

sudo: false
## Reinstate when the build can use a standard jtreg install
# addons:
#   apt:
#     packages:
#       - jtreg

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

notifications:
  email:
    - checker-framework-dev@googlegroups.com 

after_success:
  - curl -s https://raw.githubusercontent.com/mernst/plume-lib/master/bin/trigger-travis.sh > trigger-travis.sh  
  - bin/trigger-travis.sh codespecs checker-framework-demos $TRAVISTOKEN
  - bin/trigger-travis.sh codespecs checker-framework-inference $TRAVISTOKEN
  - bin/trigger-travis.sh codespecs daikon-typecheck $TRAVISTOKEN
  - bin/trigger-travis.sh codespecs plume-lib-typecheck $TRAVISTOKEN
  - bin/trigger-travis.sh codespecs sparta $TRAVISTOKEN
